#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
nohup $OPENSHIFT_DATA_DIR/bin/node $OPENSHIFT_REPO_DIR/diy/app.js >> $OPENSHIFT_DIY_LOG_DIR/app.log 2>&1&
exit 0